// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: namenode.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asignacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PosDireccion int64 `protobuf:"varint,1,opt,name=PosDireccion,proto3" json:"PosDireccion,omitempty"`
	NumChunk     int64 `protobuf:"varint,2,opt,name=NumChunk,proto3" json:"NumChunk,omitempty"`
}

func (x *Asignacion) Reset() {
	*x = Asignacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namenode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asignacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asignacion) ProtoMessage() {}

func (x *Asignacion) ProtoReflect() protoreflect.Message {
	mi := &file_namenode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asignacion.ProtoReflect.Descriptor instead.
func (*Asignacion) Descriptor() ([]byte, []int) {
	return file_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *Asignacion) GetPosDireccion() int64 {
	if x != nil {
		return x.PosDireccion
	}
	return 0
}

func (x *Asignacion) GetNumChunk() int64 {
	if x != nil {
		return x.NumChunk
	}
	return 0
}

type Propuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asignacion []*Asignacion `protobuf:"bytes,1,rep,name=asignacion,proto3" json:"asignacion,omitempty"`
	Titulo     string        `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Nchunks    int64         `protobuf:"varint,3,opt,name=Nchunks,proto3" json:"Nchunks,omitempty"`
	IdNodo     int64         `protobuf:"varint,4,opt,name=IdNodo,proto3" json:"IdNodo,omitempty"`
}

func (x *Propuesta) Reset() {
	*x = Propuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namenode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propuesta) ProtoMessage() {}

func (x *Propuesta) ProtoReflect() protoreflect.Message {
	mi := &file_namenode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propuesta.ProtoReflect.Descriptor instead.
func (*Propuesta) Descriptor() ([]byte, []int) {
	return file_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *Propuesta) GetAsignacion() []*Asignacion {
	if x != nil {
		return x.Asignacion
	}
	return nil
}

func (x *Propuesta) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Propuesta) GetNchunks() int64 {
	if x != nil {
		return x.Nchunks
	}
	return 0
}

func (x *Propuesta) GetIdNodo() int64 {
	if x != nil {
		return x.IdNodo
	}
	return 0
}

type Solicitud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namenode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_namenode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_namenode_proto_rawDescGZIP(), []int{2}
}

func (x *Solicitud) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_namenode_proto protoreflect.FileDescriptor

var file_namenode_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0a, 0x41, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x50, 0x6f, 0x73,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x75, 0x6d,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4e, 0x75, 0x6d,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x88, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x0a, 0x61, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x4e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x4e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x64, 0x4e, 0x6f,
	0x64, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x49, 0x64, 0x4e, 0x6f, 0x64, 0x6f,
	0x22, 0x1b, 0x0a, 0x09, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x32, 0x7a, 0x0a,
	0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x2f, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x72, 0x12, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x12, 0x35, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x6f, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_namenode_proto_rawDescOnce sync.Once
	file_namenode_proto_rawDescData = file_namenode_proto_rawDesc
)

func file_namenode_proto_rawDescGZIP() []byte {
	file_namenode_proto_rawDescOnce.Do(func() {
		file_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(file_namenode_proto_rawDescData)
	})
	return file_namenode_proto_rawDescData
}

var file_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_namenode_proto_goTypes = []interface{}{
	(*Asignacion)(nil), // 0: proto.Asignacion
	(*Propuesta)(nil),  // 1: proto.Propuesta
	(*Solicitud)(nil),  // 2: proto.Solicitud
}
var file_namenode_proto_depIdxs = []int32{
	0, // 0: proto.Propuesta.asignacion:type_name -> proto.Asignacion
	1, // 1: proto.ServicioNameNode.Confirmar:input_type -> proto.Propuesta
	2, // 2: proto.ServicioNameNode.SolicitarAcceso:input_type -> proto.Solicitud
	1, // 3: proto.ServicioNameNode.Confirmar:output_type -> proto.Propuesta
	2, // 4: proto.ServicioNameNode.SolicitarAcceso:output_type -> proto.Solicitud
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_namenode_proto_init() }
func file_namenode_proto_init() {
	if File_namenode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_namenode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asignacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namenode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namenode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solicitud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_namenode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_namenode_proto_goTypes,
		DependencyIndexes: file_namenode_proto_depIdxs,
		MessageInfos:      file_namenode_proto_msgTypes,
	}.Build()
	File_namenode_proto = out.File
	file_namenode_proto_rawDesc = nil
	file_namenode_proto_goTypes = nil
	file_namenode_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServicioNameNodeClient is the client API for ServicioNameNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServicioNameNodeClient interface {
	Confirmar(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Propuesta, error)
	SolicitarAcceso(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Solicitud, error)
}

type servicioNameNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioNameNodeClient(cc grpc.ClientConnInterface) ServicioNameNodeClient {
	return &servicioNameNodeClient{cc}
}

func (c *servicioNameNodeClient) Confirmar(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Propuesta, error) {
	out := new(Propuesta)
	err := c.cc.Invoke(ctx, "/proto.ServicioNameNode/Confirmar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioNameNodeClient) SolicitarAcceso(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Solicitud, error) {
	out := new(Solicitud)
	err := c.cc.Invoke(ctx, "/proto.ServicioNameNode/SolicitarAcceso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicioNameNodeServer is the server API for ServicioNameNode service.
type ServicioNameNodeServer interface {
	Confirmar(context.Context, *Propuesta) (*Propuesta, error)
	SolicitarAcceso(context.Context, *Solicitud) (*Solicitud, error)
}

// UnimplementedServicioNameNodeServer can be embedded to have forward compatible implementations.
type UnimplementedServicioNameNodeServer struct {
}

func (*UnimplementedServicioNameNodeServer) Confirmar(context.Context, *Propuesta) (*Propuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Confirmar not implemented")
}
func (*UnimplementedServicioNameNodeServer) SolicitarAcceso(context.Context, *Solicitud) (*Solicitud, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarAcceso not implemented")
}

func RegisterServicioNameNodeServer(s *grpc.Server, srv ServicioNameNodeServer) {
	s.RegisterService(&_ServicioNameNode_serviceDesc, srv)
}

func _ServicioNameNode_Confirmar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Propuesta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioNameNodeServer).Confirmar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServicioNameNode/Confirmar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioNameNodeServer).Confirmar(ctx, req.(*Propuesta))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioNameNode_SolicitarAcceso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioNameNodeServer).SolicitarAcceso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServicioNameNode/SolicitarAcceso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioNameNodeServer).SolicitarAcceso(ctx, req.(*Solicitud))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServicioNameNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServicioNameNode",
	HandlerType: (*ServicioNameNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Confirmar",
			Handler:    _ServicioNameNode_Confirmar_Handler,
		},
		{
			MethodName: "SolicitarAcceso",
			Handler:    _ServicioNameNode_SolicitarAcceso_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "namenode.proto",
}
